image:
  name: mdeterman/k8-helm3:3.14


stages:
- template
- deploy
- destroy-dry-run
- destroy


variables:
  NAMESPACE: efk
  
############## Main deploy #####################

template-elasticsearch:
  stage: template
  rules:
    - if: $CI_COMMIT_BRANCH != "destroy"

  script:
  - helm template -n ${CI_PROJECT_NAME} ${HELMCHART_NAME}
          ./${HELMCHART_PATH}/
          -f ${HELMCHART_NAME}-values.yaml
  variables:
    HELMCHART_NAME: elasticsearch
    HELMCHART_PATH: elasticsearch

template-kibana:
  stage: template
  rules:
    - if: $CI_COMMIT_BRANCH != "destroy"

  script:
  - helm template -n ${CI_PROJECT_NAME} ${HELMCHART_NAME}
          ./${HELMCHART_PATH}/
          -f ${HELMCHART_NAME}-values.yaml
  variables:
    HELMCHART_NAME: kibana
    HELMCHART_PATH: kibana

template-fluentd:
  stage: template
  rules:
    - if: $CI_COMMIT_BRANCH != "destroy"

  script:
  - helm template -n ${CI_PROJECT_NAME} ${HELMCHART_NAME}
          ./${HELMCHART_PATH}/
          -f ${HELMCHART_NAME}-values.yaml
  variables:
    HELMCHART_NAME: fluentd
    HELMCHART_PATH: fluentd

############## Main deploy #####################

deploy-elasticsearch:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  when: manual
  script:
  - helm upgrade -n ${CI_PROJECT_NAME} ${HELMCHART_NAME}
           ./${HELMCHART_PATH}/
           -f ${HELMCHART_NAME}-values.yaml
           --create-namespace
           --namespace ${NAMESPACE}
           --atomic
           --install
           --timeout 5m0s ;
  variables:
    HELMCHART_NAME: elasticsearch
    HELMCHART_PATH: elasticsearch

deploy-kibana:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  when: manual
  script:
  - helm upgrade -n ${CI_PROJECT_NAME} ${HELMCHART_NAME}
           ./${HELMCHART_PATH}/
           -f ${HELMCHART_NAME}-values.yaml
           --create-namespace
           --namespace ${NAMESPACE}
           --atomic
           --install
           --timeout 5m0s ;
  variables:
    HELMCHART_NAME: kibana
    HELMCHART_PATH: kibana

deploy-fluentd:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  when: manual
  script:
  - helm upgrade -n ${CI_PROJECT_NAME} ${HELMCHART_NAME}
           ./${HELMCHART_PATH}/
           -f ${HELMCHART_NAME}-values.yaml
           --create-namespace
           --namespace ${NAMESPACE}
           --atomic
           --install
           --timeout 5m0s ;
  variables:
    HELMCHART_NAME: fluentd
    HELMCHART_PATH: fluentd
############### END main deploy ############################

############## Main DESTROY DRY-RUN (PLAN) #####################
destroy dry-run:
  stage: destroy-dry-run
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "destroy"
  script:
  - helm uninstall -n ${NAMESPACE} --dry-run ${HELMCHART_NAME}
############### END DESTROY DRY-RUN (PLAN) ############################

############## Main DESTROY #####################
destroy (WARNING!!!):
  stage: destroy
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "destroy"
  script:
  - helm uninstall -n ${NAMESPACE} ${HELMCHART_NAME}

############### END main DESTROY ############################
