version: '3'
services:
  gitlab-runner:
    image: 'gitlab/gitlab-runner:v16.7.1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
    restart: unless-stopped
    networks:
      - gitlabnet

networks:
  gitlabnet:
    ipam:
      driver: default
      config:
         - subnet: 172.77.7.0/24